module CodeGen where

import IR

htmlHead, htmlFooter :: String
htmlHead = "<!DOCTYPE html>\n\
 \<html>\n\
 \ <head>\n\
 \  <title>\n\
 \   Generated by md2html\n\
 \  </title>\n\
 \ </head>\n\
 \ <body>\n"
htmlFooter = "</body>\n</html>"

generateHTML :: AST -> String
generateHTML ast = htmlHead ++ generateHTML' ast ++ htmlFooter

generateHTML' :: AST -> String
generateHTML' (Sequence as) =
    concat $ map generateHTML' as
generateHTML' (H i ast) =
    "<h" ++ show i ++ ">" ++ generateHTML' ast ++ "</h" ++ show i ++ ">\n"
generateHTML' (P ast)  =
    "<p>" ++ concat (map generateHTML' ast) ++ "</p>\n"
generateHTML' (Text str) = str
generateHTML' _ = ""
