module HTMLGen
  ( generateHTML
  , generateHTML'
  ) where

import           Types

htmlHead, htmlFooter :: String
htmlHead = "<!DOCTYPE html>\n\
 \<meta charset=\"utf-8\"/>\
 \<html>\n\
 \ <head>\n\
 \  <title>\n\
 \   Generated by md2html\n\
 \  </title>\n\
 \ </head>\n\
 \ <body>\n"
htmlFooter = "</body>\n</html>"

generateHTML :: AST -> String
generateHTML ast = htmlHead ++ generateHTML' ast ++ htmlFooter

generateHTML' :: AST -> String
generateHTML' (Text str) = str
generateHTML' (P ast)  =
    "<p>" ++ concatMap generateHTML' ast ++ "</p>\n"
generateHTML' (H i ast) =
    "<h" ++ show i ++ ">" ++ generateHTML' ast ++ "</h" ++ show i ++ ">\n"
generateHTML' (Sequence as) =
    concatMap generateHTML' as
generateHTML' _ = ""
